trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Instalar Node.js'

  - script: |
      yarn install --frozen-lockfile
    displayName: 'Instalar dependências'

  - script: |
      npx ng build --configuration=production --output-path=dist-front
    displayName: 'Buildar frontend'

  - task: AWSCLI@1
    inputs:
      awsCredentials: 'aws-credentials-connection'
      regionName: 'us-east-1'
      awsCommand: 's3'
      awsSubCommand: 'sync'
      awsArguments: 'dist-front s3://tcc-cesumar.com.br/ --delete'
    displayName: 'Upload do FrontEnd para o S3'
